### ISSUE TITLE
Creating Website Instead of Google Sites 

### ISSUE THREAD

**Issue by anto-mervin** [intrepidbird/intrepidbot#7]

**Comment by anto-mervin** [comment]
i can create a static website @intrepidbird ..  i can help to create a website

**Comment by intrepidbird** [comment]
sure!

**Comment by HeetVekariya** [comment]
@intrepidbird  I can create a complete backend for the project in Node.js, Express and Mongo, but first i need the frontend ready. If @anto-mervin or anyone else makes the frontend then i can start working on it.

**Comment by intrepidbird** [comment]
Sure, I'll let them know.

**Comment by anto-mervin** [comment]
@HeetVekariya  sure let's go it

**Comment by HeetVekariya** [comment]
Which techstack you are using to make the frontend ?

**Comment by HeetVekariya** [comment]
@anto-mervin Till now how much work is completed.

**Comment by intrepidbird** [comment]
I hope this is still alive 👀

**Comment by HeetVekariya** [comment]
Sorry to say that, but I am working on too many other issues. So it would be better if you can unassign me and create issues for backend of the website.

If you need any help for backend, just ping me on discord, I will be there. 👍

**Comment by intrepidbird** [comment]
OK. Sounds good 💯
